#!/usr/bin/env python3
"""
Create an interactive centroid heatmap from crop logs generated by ppe_inference.py.
By default runs a web server at http://localhost:8050 (no flags needed).

Usage:
    python3 ppe_heatmap.py                    # Start server at http://localhost:8050
    python3 ppe_heatmap.py --source /path     # Same, filter by video source
    python3 ppe_heatmap.py --save-html out/    # Save static HTML instead of serving
"""

from __future__ import annotations

import argparse
import base64
import json
import math
import os
import sys
from collections import defaultdict

import cv2
import plotly.graph_objects as go
from plotly.subplots import make_subplots


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_LOG_FILE = os.path.join(SCRIPT_DIR, "ppe_crop_centroids.jsonl")


def parse_args():
    parser = argparse.ArgumentParser(description="Interactive heatmap from PPE crop centroids")
    parser.add_argument("--log-file", default=DEFAULT_LOG_FILE, help="Path to centroid jsonl file")
    parser.add_argument("--source", default="", help="Filter by exact source video path")
    parser.add_argument("--bins-x", type=int, default=40, help="Number of heatmap bins in X direction")
    parser.add_argument("--bins-y", type=int, default=30, help="Number of heatmap bins in Y direction")
    parser.add_argument(
        "--px-per-cm",
        type=float,
        default=37.8,
        help="Pixels per centimeter used for 1x1 cm hover box grid (default: 37.8)",
    )
    parser.add_argument("--save-html", default="", help="Save static HTML instead of running server")
    return parser.parse_args()


def load_records(path):
    records = []
    if not os.path.exists(path):
        return records
    with open(path, "r", encoding="utf-8") as f:
        # Support both JSONL (one JSON object per line) and .json (single array)
        if path.lower().endswith(".json") and not path.lower().endswith(".jsonl"):
            try:
                data = json.load(f)
                if isinstance(data, list):
                    raw = data
                else:
                    raw = [data] if isinstance(data, dict) else []
            except json.JSONDecodeError:
                raw = []
        else:
            raw = []
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                    if isinstance(rec, dict):
                        raw.append(rec)
                except json.JSONDecodeError:
                    continue
        for rec in raw:
            if not isinstance(rec, dict):
                continue
            if "centroid_x" not in rec or "centroid_y" not in rec:
                continue
            records.append(rec)
    return records


def group_records_by_source(records):
    """Group centroid records by video source path. Returns dict source -> list of records."""
    by_source = defaultdict(list)
    for rec in records:
        by_source[str(rec.get("source", "unknown"))].append(rec)
    return dict(by_source)


def sanitize_filename(name):
    """Make a safe filename from a video path or name."""
    base = os.path.basename(name) if name else "unknown"
    safe = "".join(c for c in base if c.isalnum() or c in "._- ")[:80]
    return safe or "unknown"


def load_first_frame_data_uri(video_path):
    """Return (data_uri, width, height) or ("", 0, 0) on failure. Size is used to scale Image trace to heatmap coords."""
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        return "", 0, 0
    ok, frame = cap.read()
    cap.release()
    if not ok or frame is None:
        return "", 0, 0
    h, w = frame.shape[:2]
    ok, encoded = cv2.imencode(".jpg", frame)
    if not ok:
        return "", 0, 0
    b64 = base64.b64encode(encoded.tobytes()).decode("ascii")
    return f"data:image/jpeg;base64,{b64}", w, h


def _build_heatmap_data(records, args):
    """Compute heatmap grid (z, x_centers, y_centers, customdata) and (max_w, max_h)."""
    xs = [float(r["centroid_x"]) for r in records]
    ys = [float(r["centroid_y"]) for r in records]
    widths = [int(r.get("frame_width", 0)) for r in records if int(r.get("frame_width", 0)) > 0]
    heights = [int(r.get("frame_height", 0)) for r in records if int(r.get("frame_height", 0)) > 0]
    max_w = max(widths) if widths else int(max(xs) + 1)
    max_h = max(heights) if heights else int(max(ys) + 1)

    cm_px = max(1.0, float(args.px_per_cm))
    cell_w = cm_px
    cell_h = cm_px
    nx = max(1, int(math.ceil(max_w / cell_w)))
    ny = max(1, int(math.ceil(max_h / cell_h)))

    z = [[0 for _ in range(nx)] for _ in range(ny)]
    for x, y in zip(xs, ys):
        ix = min(nx - 1, max(0, int(x // cell_w)))
        iy = min(ny - 1, max(0, int(y // cell_h)))
        z[iy][ix] += 1

    x_centers = [(i + 0.5) * cell_w for i in range(nx)]
    y_centers = [(i + 0.5) * cell_h for i in range(ny)]

    customdata = []
    for iy in range(ny):
        row = []
        y0 = iy * cell_h
        y1 = min(max_h, (iy + 1) * cell_h)
        for ix in range(nx):
            x0 = ix * cell_w
            x1 = min(max_w, (ix + 1) * cell_w)
            row.append([x0, x1, y0, y1])
        customdata.append(row)

    z_plot = [[(val if val > 0 else None) for val in row] for row in z]
    return z_plot, x_centers, y_centers, customdata, max_w, max_h


def _make_heatmap_trace(z_plot, x_centers, y_centers, customdata, showscale=True):
    """Return a go.Heatmap trace for use in a figure or subplot."""
    return go.Heatmap(
        z=z_plot,
        x=x_centers,
        y=y_centers,
        zsmooth=False,
        colorscale="YlOrRd",
        colorbar={"title": "Count"} if showscale else None,
        showscale=showscale,
        customdata=customdata,
        hoverongaps=False,
        hovertemplate=(
            "1x1 cm box<br>"
            "X: %{customdata[0]:.1f} to %{customdata[1]:.1f}px<br>"
            "Y: %{customdata[2]:.1f} to %{customdata[3]:.1f}px<br>"
            "Count sum: %{z}<extra></extra>"
        ),
    )


def build_heatmap_figure(records, source_path, args):
    """Build one Plotly heatmap figure for the given list of centroid records and optional source video."""
    z_plot, x_centers, y_centers, customdata, max_w, max_h = _build_heatmap_data(records, args)
    heatmap_trace = _make_heatmap_trace(z_plot, x_centers, y_centers, customdata, showscale=True)
    heatmap_trace.opacity = 0.9

    # Build data list: image trace first (background), then heatmap (foreground)
    data = []
    if source_path and os.path.exists(source_path):
        bg_uri, img_w, img_h = load_first_frame_data_uri(source_path)
        if bg_uri and img_w > 0 and img_h > 0:
            # Anchor image bottom-left at (0,0): left at 0, bottom at 0, span [0,max_w] x [0,max_h].
            dx = max_w / img_w
            dy = -max_h / img_h
            # For Image trace, x0/y0 are the center of the first pixel (not image center).
            # So left edge is x0-dx/2 and bottom edge is y0-dy/2 (when dy<0). Set both to 0.
            image_trace = go.Image(
                source=bg_uri,
                x0=dx / 2,
                y0=max_h + dy / 2,
                dx=dx,
                dy=dy,
                opacity=0.55,
                hoverinfo="skip",
                name="",
            )
            data.append(image_trace)
    data.append(heatmap_trace)

    fig = go.Figure(data=data)

    title = "PPE Crop Centroid Heatmap"
    if source_path:
        title += f"<br><sup>{source_path}</sup>"

    fig.update_layout(
        title=title,
        xaxis_title="X (pixels)",
        yaxis_title="Y (pixels)",
        template="plotly_dark",
        width=max_w,
        height=max_h + 120,
        margin=dict(l=0, r=0, t=50, b=40),
    )
    # Fix both image and heatmap with origin at (0,0): x in [0, max_w], y in [max_h, 0]
    fig.update_xaxes(range=[0, max_w], constrain="domain")
    fig.update_yaxes(range=[max_h, 0], scaleanchor="x", scaleratio=1, constrain="domain")

    return fig


def build_all_heatmaps_figure(by_source, args):
    """Build a single figure with all heatmaps as subplots (one interface)."""
    items = sorted(by_source.items())
    n = len(items)
    if n == 0:
        return go.Figure()
    cols = min(3, n)
    rows = (n + cols - 1) // cols

    subplot_titles = [sanitize_filename(src) for src, _ in items]
    fig = make_subplots(
        rows=rows,
        cols=cols,
        subplot_titles=subplot_titles,
        vertical_spacing=0.08,
        horizontal_spacing=0.06,
    )

    for idx, (source_path, recs) in enumerate(items):
        row = idx // cols + 1
        col = idx % cols + 1
        z_plot, x_centers, y_centers, customdata, max_w, max_h = _build_heatmap_data(recs, args)
        showscale = idx == 0
        trace = _make_heatmap_trace(z_plot, x_centers, y_centers, customdata, showscale=showscale)
        fig.add_trace(trace, row=row, col=col)
        fig.update_xaxes(range=[0, max_w], row=row, col=col, title_text="X (px)" if row == rows else "")
        fig.update_yaxes(range=[max_h, 0], row=row, col=col, title_text="Y (px)" if col == 1 else "")

        # Per-subplot video frame: use paper coords and subplot domain so image appears in this subplot
        if source_path and os.path.exists(source_path):
            bg_uri, _, _ = load_first_frame_data_uri(source_path)
            if bg_uri:
                # Subplot domains (0-1) from make_subplots: row 1 at top, row N at bottom
                xaxis_key = "xaxis" if idx == 0 else f"xaxis{idx + 1}"
                yaxis_key = "yaxis" if idx == 0 else f"yaxis{idx + 1}"
                x_domain = getattr(fig.layout, xaxis_key).domain
                y_domain = getattr(fig.layout, yaxis_key).domain
                fig.add_layout_image(
                    dict(
                        source=bg_uri,
                        xref="paper",
                        yref="paper",
                        x=x_domain[0],
                        y=y_domain[1],
                        sizex=x_domain[1] - x_domain[0],
                        sizey=y_domain[0] - y_domain[1],
                        sizing="stretch",
                        opacity=0.55,
                        layer="below",
                        xanchor="left",
                        yanchor="top",
                    )
                )
                fig.data[idx].update(opacity=0.9)

    fig.update_layout(
        title_text="PPE Crop Centroid Heatmaps (all sources)",
        template="plotly_dark",
        height=280 * rows + 80,
        showlegend=False,
    )
    return fig


def build_all_heatmaps_single_html(by_source, args, save_path=""):
    """
    Build one HTML file with multiple standalone heatmap figures (each with video frame).
    Each figure is built with build_heatmap_figure so the background image is guaranteed to show.
    Returns (html_string, None) for writing to file; no go.Figure for fig.show().
    """
    items = sorted(by_source.items())
    if not items:
        return "", None

    plotly_js_url = "https://cdn.plot.ly/plotly-2.27.0.min.js"
    parts = [
        "<!DOCTYPE html>",
        "<html><head><meta charset='utf-8'><title>PPE Heatmaps</title>",
        f"<script src='{plotly_js_url}'></script>",
        "<style>",
        "body { font-family: sans-serif; background: #1a1a1a; color: #eee; margin: 12px; }",
        ".heatmap-block { margin-bottom: 32px; }",
        ".heatmap-block h2 { margin: 8px 0; font-size: 1.1em; }",
        "</style>",
        "</head><body>",
        "<h1>PPE Crop Centroid Heatmaps</h1>",
    ]
    div_id = 0
    for source_path, recs in items:
        fig = build_heatmap_figure(recs, source_path, args)
        div_id += 1
        title = sanitize_filename(source_path)
        parts.append(f"<div class='heatmap-block'><h2>{title}</h2>")
        parts.append(
            fig.to_html(
                full_html=False,
                include_plotlyjs=False,
                div_id=f"heatmap_{div_id}",
            )
        )
        parts.append("</div>")
    parts.append("</body></html>")
    return "\n".join(parts), None


def make_app(args):
    """Create Flask app for real-time heatmap interface."""
    try:
        from flask import Flask, jsonify, render_template_string
    except ImportError:
        sys.exit("Install Flask to run the server: pip install flask")

    app = Flask(__name__)

    def get_by_source():
        records = load_records(args.log_file)
        if not records:
            return None, []
        by_source = group_records_by_source(records)
        if args.source.strip():
            src = args.source.strip()
            if src not in by_source:
                return None, []
            by_source = {src: by_source[src]}
        return by_source, sorted(by_source.items())

    @app.route("/api/figures")
    def api_figures():
        by_source, items = get_by_source()
        if not items:
            return jsonify({"error": "No centroid records found", "figures": []}), 200
        figures = []
        titles = []
        for source_path, recs in items:
            fig = build_heatmap_figure(recs, source_path, args)
            figures.append(fig.to_dict())
            titles.append(sanitize_filename(source_path))
        return jsonify({"figures": figures, "titles": titles})

    INDEX_HTML = """<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>PPE Heatmaps</title>
  <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
  <style>
    body { font-family: sans-serif; background: #1a1a1a; color: #eee; margin: 12px; }
    h1 { margin-bottom: 8px; }
    .heatmap-block { margin-bottom: 32px; }
    .heatmap-block h2 { margin: 8px 0; font-size: 1.1em; }
    .refresh { margin-bottom: 12px; }
    .refresh button { padding: 8px 16px; cursor: pointer; font-size: 14px; }
    a { color: #7dd; }
  </style>
</head>
<body>
  <h1>PPE Crop Centroid Heatmaps</h1>
  <p>Live at <a href="">this URL</a>. Data is reloaded when you click Refresh.</p>
  <div class="refresh"><button type="button" id="refresh">Refresh data</button></div>
  <div id="heatmaps"></div>
  <script>
    function render(figures, titles) {
      const container = document.getElementById('heatmaps');
      container.innerHTML = '';
      if (!figures || figures.length === 0) {
        container.innerHTML = '<p>No data. Add centroid records to the log file and click Refresh.</p>';
        return;
      }
      figures.forEach((fig, i) => {
        const div = document.createElement('div');
        div.className = 'heatmap-block';
        const h2 = document.createElement('h2');
        h2.textContent = titles[i] || ('Source ' + (i + 1));
        div.appendChild(h2);
        const plotDiv = document.createElement('div');
        plotDiv.id = 'plot-' + i;
        plotDiv.style.width = '100%';
        div.appendChild(plotDiv);
        container.appendChild(div);
        Plotly.newPlot(plotDiv.id, fig.data, fig.layout, { responsive: true });
      });
    }
    function load() {
      fetch('/api/figures')
        .then(r => r.json())
        .then(d => { render(d.figures || [], d.titles || []); })
        .catch(e => { document.getElementById('heatmaps').innerHTML = '<p>Error: ' + e + '</p>'; });
    }
    document.getElementById('refresh').onclick = load;
    load();
  </script>
</body>
</html>"""

    @app.route("/")
    def index():
        return render_template_string(INDEX_HTML)

    return app


HEATMAP_PORT = 8050  # real-time interface runs on this port


def main():
    args = parse_args()

    # Default: run web server. Use --save-html to export static HTML instead.
    if not args.save_html.strip():
        app = make_app(args)
        print(f"PPE Heatmap: http://localhost:{HEATMAP_PORT}")
        print("Press Ctrl+C to stop.")
        app.run(host="0.0.0.0", port=HEATMAP_PORT, debug=False, threaded=True)
        return

    records = load_records(args.log_file)
    if not records:
        print(f"No centroid records found in: {args.log_file}")
        sys.exit(1)

    by_source = group_records_by_source(records)
    selected_source = args.source.strip()

    if selected_source:
        if selected_source not in by_source:
            print(f"No records found for source: {selected_source}")
            sys.exit(1)
        by_source = {selected_source: by_source[selected_source]}

    save_base = args.save_html.strip()
    is_save_dir = save_base.endswith(os.sep) or (save_base and os.path.isdir(save_base))
    if is_save_dir:
        os.makedirs(save_base, exist_ok=True)

    if len(by_source) == 1:
        source_path, recs = next(iter(by_source.items()))
        fig = build_heatmap_figure(recs, source_path, args)
        if save_base:
            out_path = save_base if not is_save_dir else os.path.join(save_base, f"heatmap_{sanitize_filename(source_path)}.html")
            fig.write_html(out_path, include_plotlyjs="cdn")
            print(f"Saved heatmap HTML to: {out_path}")
        fig.show()
    else:
        # Multiple sources: one HTML with one full figure per source (each with video frame visible)
        html_str, _ = build_all_heatmaps_single_html(by_source, args)
        out_path = None
        if save_base:
            out_path = save_base if not is_save_dir else os.path.join(save_base, "heatmaps_all.html")
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(html_str)
            print(f"Saved all heatmaps HTML to: {out_path}")
        # Open in browser so user sees the page with frames
        if html_str:
            import tempfile
            import webbrowser
            if out_path:
                path = os.path.abspath(out_path)
            else:
                fd, path = tempfile.mkstemp(suffix=".html", prefix="ppe_heatmaps_")
                os.close(fd)
                with open(path, "w", encoding="utf-8") as f:
                    f.write(html_str)
            webbrowser.open(f"file://{path}")


if __name__ == "__main__":
    main()

